import { Review } from './types';

export const reviewData: Review[] = [
  {
    id: 1,
    name: 'AlexGamer23',
    content: 'Really fun game! Love the progression system.',
    rating: 5,
    approved: true,
    createdAt: '2025-06-01T10:15:30Z',
  },
  {
    id: 2,
    name: 'CasualPlayer99',
    content: 'Good idle mechanics, but the UI could use some polish.',
    rating: 4,
    approved: true,
    createdAt: '2025-06-03T08:42:10Z',
  },
  {
    id: 3,
    name: 'GameCriticX',
    content: 'Interesting concept, but gets repetitive quickly.',
    rating: 3,
    approved: true,
    createdAt: '2025-06-05T14:28:05Z',
  },
  {
    id: 4,
    name: 'IdleKing',
    content: 'Loving the artifact system! It adds a lot of depth.',
    rating: 5,
    approved: true,
    createdAt: '2025-06-06T18:05:45Z',
  },
  {
    id: 5,
    name: 'BetaTesterJoe',
    content: 'I encountered a few bugs, but overall it’s promising.',
    rating: 3,
    approved: true,
    createdAt: '2025-06-07T12:01:00Z',
  },
  {
    id: 6,
    name: 'QuickTapper',
    content: 'Addictive gameplay! Can’t wait for future updates.',
    rating: 4,
    approved: true,
    createdAt: '2025-06-08T09:23:11Z',
  },
  {
    id: 7,
    name: 'LunaDev',
    content: 'A great example of what an indie game can achieve.',
    rating: 5,
    approved: true,
    createdAt: '2025-06-09T16:45:20Z',
  },
];
